name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export PATH="$PATH:/home/artistshero/.nvm/versions/node/v18.16.0/bin/"
            cd /home/artistshero/www/ah-admin/
            rm -rf node_modules/ dist/ .cache/ package-lock.json pnpm-lock.yaml yarn.lock
            git pull
            npm install
            npm run build
            pm2 restart ah-strapi-admin
